---
- name: Provision the new system with our standards
  hosts: "{{ HOSTS | default ('all') }}"
  gather_facts: False

  vars:
  - gokev_custom_vars:
    - piece1: Piece one
      relevance: minimal
    - piece2: Piece two
      relevance: medium
    - piece3: Piece three
      relevance: extreme

  tasks:

  - name: debug the vars
    debug:
      var: gokev_custom_vars

  - name: custom facts dir
    file:
      path: /etc/ansible/facts.d/
      state: directory
      mode: '0755'

  - name: custom facts to path
    copy:
      content: "{{ gokev_custom_vars | to_json }}"
      dest: /etc/ansible/facts.d/gokev_custom_vars.fact
      owner: root
      group: root
      mode: 0644

  - name: "Re-run setup to use custom facts"
    setup: ~

