---
- name: Provision the new system with our standards
  hosts: "{{ HOSTS | default ('all') }}"
  gather_facts: False

  vars:
    gokev_custom_vars:
      - days:
        - today:
          - shopping:
            - costco:
                - product: salsa
                  size: gallon
                  quantity: 3
                - product: gasoline
                  size: gallons
                  quantity: fill
                - product: organic tortilla chips
                  quantity: 17 bags
                - product: Charleston Organic Coffee
                  size: 2lb bag
                  quantity: 4
            - walmart:
              - no_trip_needed
          - to_do:
            - skoolie:
              - interior:
                - 'remove seats'
              - wiring:
                - 'install backup cameras'
                - 'install automatic starter'
                - 'modify door switch for remote'
              - trailer:
                - 'run trailer light wires to rear'
                - 'install 7 pin round plug in rear'
              - paint_and_body:
                - 'apply rust converter'
                - 'stage generator for fitment'
        - tomorrow:
          - to_do:
            - skoolie:
              - interior:
                - 'remove remaining roof panels'
              - wiring:
                - 'program remote starter for disel delay'
              - trailer:
                - 'install trailer hitch'
              - paint_and_body:
                - 'remove adhesive'
                - 'wire wheel rough-up'
        - nextweek:
          - to_do:
            - skoolie:
              - interior:
                - 'clean out all tools and trash'
              - wiring:
                - 'wrap interior wires out of the way'
              - paint_and_body:
                - 'mount backup camera'
                - 'stage and evaluate locations for side cameras'


  tasks:

  - name: debug the vars
    debug:
      var: gokev_custom_vars

  - name: custom facts dir
    file:
      path: /etc/ansible/facts.d/
      state: directory
      mode: '0755'

  - name: custom facts to path
    copy:
      content: "{{ gokev_custom_vars | to_json }}"
      dest: /etc/ansible/facts.d/gokev_custom_vars.fact
      owner: root
      group: root
      mode: 0644

  - name: "Re-run setup to use custom facts"
    setup: *

